apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefun-app
  namespace: kubefun
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: kubefun-app
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
