# manifests/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefun-app
  namespace: kubefun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubefun-app
  template:
    metadata:
      labels:
        app: kubefun-app
    spec:
      serviceAccountName: kubefun-app-sa
      containers:
        - name: kubefun-app
          image: oxfordfun/kubefun:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: kubefunb-aws-env
