# manifests/base/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubefun-app-binding
subjects:
  - kind: ServiceAccount
    name: kubefun-app-sa
    namespace: kubefun
roleRef:
  kind: ClusterRole
  name: kubefun-app-role
  apiGroup: rbac.authorization.k8s.io
